# Generated by Django 5.1.5 on 2026-01-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userservicearea'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('tradesperson', 'Tradesperson'), ('visitor', 'Visitor / Customer')], db_index=True, default='tradesperson', max_length=20),
        ),
    ]
