# Generated by Django 5.1.5 on 2026-01-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('tradesperson', 'Tradesperson'), ('visitor', 'Visitor')], db_index=True, default='tradesperson', max_length=20),
        ),
    ]
