# Generated by Django 5.1.5 on 2026-01-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_summary',
            field=models.TextField(blank=True, help_text='Short bio about your business, experience, and what you specialize in.', max_length=1000, null=True),
        ),
    ]
