# Generated by Django 5.1.5 on 2026-01-04 23:42

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_tradeworkphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeworkphoto',
            name='image',
            field=models.ImageField(upload_to=users.models.work_photo_upload_path, validators=[users.models.validate_gallery_image_size]),
        ),
    ]
