# Generated by Django 5.1.5 on 2026-01-11 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_license'),
    ]

    operations = [
    ]


def populate_provinces(apps, schema_editor):
    Province = apps.get_model("users", "Province")

    provinces = [
        ("AB", "Alberta"),
        ("BC", "British Columbia"),
        ("MB", "Manitoba"),
        ("NB", "New Brunswick"),
        ("NL", "Newfoundland and Labrador"),
        ("NS", "Nova Scotia"),
        ("NT", "Northwest Territories"),
        ("NU", "Nunavut"),
        ("ON", "Ontario"),
        ("PE", "Prince Edward Island"),
        ("QC", "Quebec"),
        ("SK", "Saskatchewan"),
        ("YT", "Yukon"),
    ]

    for code, name in provinces:
        Province.objects.get_or_create(
            code=code,
            defaults={"name": name}
        )


